---
swagger: 2.0
info:
  title: ServerlessResizeApi
paths:
  /:
    get:
      x-amazon-apigateway-integration:
        uri: arn:aws-cn:apigateway:REGION:lambda:path/2015-03-31/functions/arn:aws-cn:lambda:REGION:ACCOUNT_ID:function:${stageVariables.LambdaFunctionName}/invocations
        type: AWS_PROXY
        httpMethod: post
